# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: s3-sftp

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'
    main: ./cmd/s3-sftp
    ldflags:
      - -s -w -X main.Version={{.Tag}} -X main.Commit={{.ShortCommit}} -X main.BuildTime={{.Date}}
    id: "s3-sftp"
    binary: "s3-sftp"

archives:
  - formats: ['tar.gz']
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README*
      - LICENSE*

checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
  algorithm: sha256

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Tag }}-source"